apiVersion: v2
name: postgresql
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "17.6-alpine" # PostgreSQL version
# No dependencies: using official postgres image