apiVersion: v2
name: postgresql
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "1.16.0"
dependencies:
  - name: postgresql
    version: "16.0.2"
    repository: "https://charts.bitnami.com/bitnami"