apiVersion: v2
name: postgresql
description: A Helm chart for Kubernetes
dependencies:
  - name: postgresql
    version: "16.0.2"
    repository: "https://charts.bitnami.com/bitnami"

version: 0.1.0
appVersion: "1.16.0"
type: application
