apiVersion: v2
name: postgresql
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "17.6.0" # PostgreSQL version
dependencies:
  - name: postgresql
    version: "16.7.27"
    repository: "https://charts.bitnami.com/bitnami"