---
# Source: forgejo/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: forgejo-blue
  namespace: development
spec:
  selector:
    app: forgejo-blue
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
---
# Source: forgejo/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgejo-blue
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forgejo-blue
  template:
    metadata:
      labels:
        app: forgejo-blue
    spec:
      containers:
        - name: forgejo
          image: codeberg.org/forgejo/forgejo:13.0.3
          ports:
            - containerPort: 3000
---
# Source: forgejo/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: forgejo-ingress
  namespace: development
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: forgejo.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: forgejo-blue
                port:
                  number: 3000
